version: "3.7"

services:
  php:
      build: docker/php
      restart: always
      volumes:
          - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
          - ./app:/var/www/html

  composer:
      image: composer
      volumes:
          - ./app:/app

  nginx:
    image: nginx
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html
    ports:
        - 8080:80
    restart: always
    depends_on:
        - php
