version: "3.7"

services:
  php:
    dns:
      - 172.53.0.53
    networks:
      - dns-network

  nginx:
    dns:
      - 172.53.0.53
    networks:
      - dns-network

networks:
  dns-network:
    external: true
